### ISSUE TITLE
Include CEF´s libs

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [WootsMX/insource#12]
It would be good if you included the CEF's precompiled Libs (and their respective DLLs ) for some would be difficult to compile CEF

**Comment by kolessios** [comment]
Because they are very heavy and this caused me problems in the past when uploading it to Git, I decided to upload them independently

CEF Libs:
https://drive.google.com/open?id=0B9QgMNC5et3nM2hlTWp6aWthTzg
_(src/lib/common)_

CEF Bin's:
https://drive.google.com/open?id=0B9QgMNC5et3nTjZvNGRXM3ZyXzQ
_(game/bin/)_
